charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
Hello, this PR adds `extraArgs` support into Atlantis running container. 
This is a pattern commonly used by other opensource charts:
* https://github.com/prometheus-community/helm-charts/blob/b0ebaff7c3dc5e9038e0dc5a4931b8b7ba18fad2/charts/kube-prometheus-stack/values.yaml#L1251
* https://github.com/bitnami/charts/blob/c2ac165a579a8f06dede2b6fede2f4ec2bfea495/bitnami/kube-prometheus/values.yaml#L1351
* https://github.com/traefik/traefik-helm-chart/blob/bbad36d8b871e35f1c2290b1a033d2f01c9a94ab/traefik/values.yaml#L119
I made this because we want to use the `--disable-repo-locking` argument introduced in Atlantis v0.16.1
=> Add extraArgs into StatefulSet

charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
The requirements of my base container force me to use a different uid, this patch helps me use the upstream chart while still using a custom Atlantis container.
=> Allow overriding fsGroup/runAsUser in statefulset if necessary

charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
Add flag to enable https://github.com/runatlantis/atlantis/pull/1751 so that we can use color comments. Defaulted to false so no change by default.
=> Add Markdown Diff Flag

charts/atlantis/values.yaml
The readme states the default value for this as `/`, and without it, deploying the chart fails.
=> Set default ingress.path to /

README.md, charts/atlantis/templates/_helpers.tpl, charts/atlantis/templates/secret-basic-auth.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
With the [runatlantis/atlantis v0.17.5](https://github.com/runatlantis/atlantis/releases/tag/v0.17.5) release, users are allowed to configure a basic authentication. The helm chart does not allow the `livenessProbe` and `readinessProbe` to add custom headers, so this PR adds support for both the creation of credentials and probes.
In this PR you will find:
* Updated values
* Updated README
* A secret resource holding credentials
* Modified StatefulSet resource to inject the environments required by the basic authentication configuration (`ATLANTIS_WEB_BASIC_AUTH`, `ATLANTIS_WEB_USERNAME`, `ATLANTIS_WEB_PASSWORD`)
* [Removed] Modified `livenessProbe` and `readinessProbe` to add a basic authorization header
Tested it manually, deploying atlantis in an EKS cluster.
Edit:
There's no need for …
=> Allow configuring of basic authentication

charts/atlantis/values.yaml
Having the default basicAuth block uncommented under values as
introduced in #98 causes this chart to be backwards incompatible with
existing installations.
=> fix: disable basic auth by default

charts/atlantis/templates/secret-webhook.yaml, charts/atlantis/templates/statefulset.yaml
the existing githubApp logic results in 
```shell
Warning  FailedCreate      5m6s (x18 over 16m)  statefulset-controller  create Pod atlantis-0 in StatefulSet atlantis failed error: Pod "atlantis-0" is invalid: [spec.volumes[1].secret.items[0].path: Invalid value: "/key.pem": must be a relative path, spec.containers[0].volumeMounts[1].name: Not found: "github-app-key-volume"]
```
also
`{{- if index .Values.githubApp "key.pem"}}` is kind of messy with indexing values and the helm conventions strongly suggest 
> Variable names should begin with a lowercase letter, and words should be separated with camelcase
=> fix: avoid '"/key.pem": must be a relative path'

charts/atlantis/templates/ingress.yaml
When deploying to a cluster version 1.18 this chart incorrectly tries to use `networking.k8s.io/v1`. This seems to be due to the `networking.k8s.io` existing for some resource kinds, but not for `Ingress`. For example [NetworkPolicy](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).
The solution is to check for `networking.k8s.io/v1/Ingress` or `networking.k8s.io/v1beta/Ingress`. 
There was also an issue with line 48. When the chart was able to choose the correct version the formatting was wrong. 
Tested this change using kind on k8s versions 1.18 through 1.23. 
Fixes https://github.com/runatlantis/helm-charts/issues/96
Here is a similar issue on another project for reference: https://gitea.com/gitea/helm-chart/issues/77
I realize v1.18 is really old, but some of us have …
=> Modify ingress template to choose the proper group/version for clusters <=1.18.

charts/atlantis/templates/statefulset.yaml
=> Switch atlantis url to https when relying on ingress

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Emergency update due to a bug found with 0.18.4 (https://github.com/runatlantis/atlantis/issues/2104)
relates to https://github.com/runatlantis/atlantis/pull/2107
=> update default atlantis to 0.18.5

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
it _seems_ as though starting from atlantis 0.18.5 dockerhub support has been dropped. 
this uses ghcr instead
https://github.com/runatlantis/atlantis/releases/tag/v0.18.5
---
fixes https://github.com/runatlantis/atlantis/issues/2110
relates to https://github.com/runatlantis/atlantis/pull/2107
=> fix: use ghcr instead of dockerhub

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml
Only setting `vcsSecretName` was not enough to get Github App working, since some **StatefulSet** configuration are valid only if `githubApp.key or githubApp.secret`  have values.
for now I'm using something like this
```yaml
githubApp:
id: 123456
key: fake
secret: fake
vcsSecretName: "github-secrets"
```
`github-secrets` is a secret created outside the chart and setting dummy values for key and secret works just fine but I'm not sure if this is intended.
=> fix: use github app config from external secret

README.md, charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
I would like to customize the terminationGracePeriodSeconds of the Statefull Set. 
Please find that config setting inside this PR.
- Updateded readme
- Updated values.yaml
- Added terminationGracePeriodSeconds as conditional, so that it can fall back to the Kubernetes default
Test:
- Tested it manually, deploying atlantis wits terraform helm_releease inside a GKE cluster. Works fine.
=> feat: optionally allow to customize the terminationGracePeriodSeconds of the Statefull Set

charts/atlantis/templates/statefulset.yaml
Fixes #74.
Using [best practice from helm](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) for automatically rolling deployments.
=> incld. configmap checksum as annotation (#74)

charts/atlantis/values.yaml
If I understand it correctly here "containers" should be "extraContainers", to be in line with the declaration above.
=> Fixed extraContainers struct in values.yaml

README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
The Atlantis docs say that `--repo-whitelist` is deprecated for `--repo-allowlist`. This PR adds a `orgAllowlist` value to the chart and deprecates `orgWhitelist`, and in the template `orgAllowlist` takes precedence over the deprecated `orgWhitelist`
=> Add orgAllowlist value and deprecate orgWhitelist

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
reverting #21 
more information here : https://github.com/runatlantis/helm-charts/issues/14
=> Revert Security Context Change

charts/atlantis/values.yaml
Use `fsGroupChangePolicy: "OnRootMismatch"` (stable in k8s 1.23) to eliminate unnecessary chmod that can be slow for large volumes.
See https://github.com/runatlantis/helm-charts/issues/14
See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
=> Fix slow startup by doing chmod once

README.md, charts/atlantis/templates/_helpers.tpl, charts/atlantis/templates/secret-api.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
With [v0.19.8](https://github.com/runatlantis/atlantis/releases/tag/v0.19.8), there is now a programmatic API available for Atlantis. This PR adds the ability to enable the API.
=> Adding ability to set API Secret to enable API endpoints

charts/atlantis/values.yaml
- Add /* as a default ingress path
- This will allow access to / and other common atlantis api paths
- closes https://github.com/runatlantis/helm-charts/issues/166
=> Add /* as a default ingress path

charts/atlantis/templates/podmonitor.yaml
Description:
namespaceSelector is not supported in PodMonitor `spec.selector` and set nindent 6 instead of 4
Ref: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/v0.4.3-gke.0/doc/api.md#podmonitoringspec
Error message:
```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(PodMonitoring.spec): unknown field "namespaceSelector" in com.googleapis.monitoring.v1.PodMonitoring.spec, ValidationError(PodMonitoring.spec.selector): unknown field "app" in com.googleapis.monitoring.v1.PodMonitoring.spec.selector
```
=> removing namespaceSelector in PodMonitor

charts/atlantis/Chart.yaml, charts/atlantis/templates/servicemonitor.yaml
- fixing ident on template for serviceMonitor
Seeing error when trying to apply
```
Error: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "chart" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "heritage" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "release" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector]
```
=> fix: service monitor spacing

charts/atlantis/templates/statefulset.yaml
coalesce isn't properly fallbacking `orgAllowlist` to `orgWhitelist` because there is a default value for `orgAllowlist` (*\<replace-me>*)
=> fix orgWhitelist fallback #154

charts/atlantis/templates/podmonitor.yaml
with the current `matchLabels` set in PodMonitor `selector`.
Google Managed Prometheus won't add it into metrics collector because it is difference with [atlantis container's labels](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/statefulset.yaml#L23).
=> fix matchLabels in PodMonitor selector

charts/atlantis/Chart.yaml, charts/atlantis/templates/ingress.yaml, charts/atlantis/values.yaml
- Allow optional host to be set
- Fix linting issue
> An optional host. In this example, no host is specified, so the rule applies to all inbound HTTP traffic through the IP address specified. If a host is provided (for example, foo.bar.com), the rules apply to that host.
https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
- Closes https://github.com/runatlantis/helm-charts/issues/201
- https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
This command used to return just `rules` but now it will return the paths without the `host` if the `host` is omitted.
```sh
helm template . -s templates/ingress.yaml \
--set "ingress.host=" \
--set "ingress.hosts=null" | yq .spec
```
Before this change
```yaml
rules:
```
After this proposed change …
=> Allow optional host to be set

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml
Adds quotes to Locking DB and Redis values.
Fixes issue where providing a number or boolean value fails Helm chart installation.
Previous PR https://github.com/runatlantis/helm-charts/pull/211
=> fix: Quote Locking DB and Redis values

charts/atlantis/Chart.yaml, charts/atlantis/templates/ingress.yaml
When setting ingress.apiVersion to networking.k8s.io/v1 and  ingress.hosts , the rendered ingress manifest is broken
=> fix: #216 fix ingress manifest template

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml
Hot fix from 
https://github.com/runatlantis/helm-charts/pull/209
the value from`shareProcessNamespace` was pulling from the wrong location. This is a hot patch for it.
=> shareProcessNamespace hot patch

charts/atlantis/Chart.yaml, charts/atlantis/templates/secret-webhook.yaml, charts/atlantis/templates/statefulset.yaml
When using GitHub Enterprise, `github.hostname` has to be set. If Atlantis uses a GitHub App for it's setup, the `github.user`, `github.token`,`github.secret` values are not needed, and it causes issues and conflicts when it's set.
To avoid this, the `github.user` value should be checked instead of just `github`, since the other two values are required for that setup.
Because `github.user` is already a required field, this should keep the chart backwards compatible, and it shouldn't be a breaking change, but it should let future chart versions use GitHub Enterprise with a GitHub App.
=> Require GitHub configuration only if bot user is used

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Fix github default value missing
It fixes #236 
n/a
- closes #236
- closes https://github.com/runatlantis/helm-charts/pull/235
=> Fix github default value missing

.github/workflows/release.yaml
Bump helm to the latest version
The pipeline is failing, because `3.10` is not a valid version number. It should be `3.10.0` or `3.10.3`, which is the latest.
[Failed run](https://github.com/runatlantis/helm-charts/actions/runs/3859256677/jobs/6578609819)
[Helm 3.10.0](https://github.com/helm/helm/releases/tag/v3.10.0)
[Helm 3.10.3](https://github.com/helm/helm/releases/tag/v3.10.3)
=> chore(workflows): define setup-helm action patch version

.github/workflows/release.yaml
- Chart-releaser seems to be failing to update the index.yaml in the gh-pages branch. 
Hoping a combination of bumping the action and also manually bringing the index.yaml update up to date will help.
https://github.com/runatlantis/helm-charts/pull/253
https://github.com/runatlantis/helm-charts/actions/runs/3969254151/attempts/1
=> chore(ci): bump chart-releaser action to v1.5

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
- set pullPolicy to `Always` with `latest` tag
- since we're using latest to avoid having to update this repo for each new version of atlantis, we also need to bump the pull policy so it pulls the latest image when a new one is uploaded
- consistency with runatlantis/atlantis kustomize
- consistency with terraform aws modules atlantis
- Previous pr #265 
- appVersion is optional https://helm.sh/docs/topics/charts/#the-chartyaml-file
- [latest usage in terraform-aws-atlantis module](https://github.com/terraform-aws-modules/terraform-aws-atlantis/blob/9d4e8ebb668a4b0637bcc0f6a1a2364229275c19/variables.tf#LL552C17-L552C23)
- feedback from @dschunack https://github.com/runatlantis/helm-charts/pull/265#discussion_r1122816742
=> fix: set pullPolicy to `Always` with `latest` tag

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
- fix: Use app version instead of latest
- bump to 0.23.2
- revert back to using app Version instead of latest. While it's easier for maintenance for us to use latest, it's not considered best practices.
- This is the previous logic.
- previous pr #265 
- previous pr #266 
- https://github.com/runatlantis/atlantis/releases
=> fix: Use app version instead of latest

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml
- Fix helm chart issues, `topologySpreadConstraints` is inside `tolerations` block
- Use standardized convention 
- Helm template is giving errors if there's values in `tolerations`
- previous pr #264
=> fix(tolerations): resolve placement errors

charts/atlantis/Chart.yaml
Update to latest Stable release.
https://github.com/runatlantis/atlantis/releases/tag/v0.23.3
* Update to latest release https://github.com/runatlantis/atlantis/releases/tag/v0.23.3
=> Update App Version to v0.23.3

.github/workflows/release.yaml, charts/atlantis/Chart.yaml
Fix chart pointing to the wrong atlantis version
broken link
=> fix: update app version link for 0.23.3 release

charts/atlantis/Chart.yaml, charts/atlantis/templates/tests/test-atlantis-pod.yaml
Users that deploy Atlantis with tests enabled experience the following error:
```
Failed to pull image "dduportal/bats:0.4.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for dduportal/bats, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
dduportal/bats is no longer available at the repository specified. We need to switch to another repo.
https://github.com/dduportal-dockerfiles/bats/issues/10
https://github.com/helm/charts/pull/19526
=> fix(tests): switch dduportal/bats to bats/bats

.github/workflows/lint-test.yaml
Update helm/chart-testing action to the latest [example workflow](https://github.com/helm/chart-testing-action/tree/v2.4.0/#example-workflow)
Looks like the action has been failing silently with the warnings:
N/A
Bump chart was not detected by the action -> https://github.com/runatlantis/helm-charts/pull/297#issuecomment-1568497204
=> ci(helm/chart-testing): update github action

charts/atlantis/Chart.yaml, charts/atlantis/ci/ci-values.yaml, charts/atlantis/templates/tests/test-atlantis-configmap.yaml, charts/atlantis/templates/tests/test-atlantis-pod.yaml, charts/atlantis/values.yaml
- Fix helm test
- Simplify logic by using the bats image directly
- Closes https://github.com/runatlantis/helm-charts/issues/292
- Tested locally with:
```sh
kind create cluster --name test-atlantis
helm upgrade -i atlantis charts/atlantis -f ci/ci-values.yaml
helm test atlantis
kind delete cluster --name test-atlantis
```
=> ci(helm): fix and simplify bats logic

charts/atlantis/Chart.yaml, charts/atlantis/ci/ci-values.yaml, charts/atlantis/templates/secondary-ingress.yaml, charts/atlantis/values.yaml
Allow creating a secondary ingress
We want to be able to expose Atlantis to gitlab webhooks coming one network, while only allowing access to the Atlantis UI from our internal network/
- closes #282
=> feat(ingress): Allow creating secondary ingress

charts/atlantis/Chart.yaml, charts/atlantis/templates/tests/test-atlantis-pod.yaml, charts/atlantis/values.yaml
Also added annotations for test pod manifest.
Remove random prefix for test pod name.
Also added annotations for test pod manifest.
It is bad practice to user random prefix in name.
- this leads to problems when using kustomize because the searching resource is implemented via name search.
- if it necessary, random value can be passed via annotation.
- in some cases generated templates need to be without diff.
local, by compare templates
with empty and filled .Values.test.annotations
=> Remove random prefix for test pod

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Remove cpu limits from the atlantis container
Atlantis simply dies on simple tasks like `terraform init` with the current configuration.
https://home.robusta.dev/blog/stop-using-cpu-limits
=> fix: don't define resources

charts/atlantis/Chart.yaml
- bump app version to 0.24.4
https://github.com/runatlantis/atlantis/releases/tag/v0.24.4
=> feat: bump app version to 0.24.4

charts/atlantis/Chart.yaml
relates to https://github.com/runatlantis/atlantis/releases/tag/v0.25.0
=> release: bump atlantis to 0.25.0

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
What it says in the title
Our atlantis instance runs in an EKS IPv6-only cluster, and thus cannot contact the EKS control plane (which is ipv4-only) if not run with hostNetwork, as the nodes are dual stack.
None
=> feat: add support for hostNetwork

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
- Allow the path to the Atlantis Data directory to be configured.
- When we initially deployed Atlantis we preferred the data directory path to be differently named. We now have custom workflows that refer to our custom path name.
- Used modified chart to deploy to our test and production environments.
none
=> feat: allow configurable data directory path

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Commenting out the default password and username setting for service monitor authentication to avoid running into the checkov SECRET_6 compliance check.
Since its disabled by default any way there should be no harm in commenting out the actual setting of the password and prevents people from deploying with a default password if they do enable the auth check for the service monitor. Commented out and left for reference of users that want to set it.
Running checkov against charts with it commented out does not make the error occur.
=> commenting out default servicemonitor auth to avoid checkov CKV_SECRET_6

charts/atlantis/Chart.yaml
[v0.26.0](https://github.com/runatlantis/atlantis/releases/tag/v0.26.0) was released a few weeks ago
=> release: update atlantis to v0.26.0

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Add missing values to the values.schema.json
-  closes #331
=> Fix: add fullnameOverride, nameOverride and global to values.schema.json

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
Add loadBalancerSourceRanges to schema
The loadBalancerSourceRanges is an existing param in the chart, but passing it to the chart after the schema was added results in `- service: Additional property loadBalancerSourceRanges is not allowed` error.
Applied with passing the value and without passing the value.
=> Add loadBalancerSourceRanges to schema

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Add missing value (command) to the values.schema.json
- Use closes #335
=> Fix: add command to values.schema.json

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json
Update the JSON schema to reflect that `containerSecurityContext` in `values.yaml` can be an instance of [`io.k8s.api.core.v1.SecurityContext`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#securitycontext-v1-core)
To allow the full range of Security Context settings, for instance, we use `capabilities`.
Checked with https://www.jsonschemavalidator.net/
N/A
=> Fix values.schema.json -  containerSecurityContext is an instance of io.k8s.api.core.v1.SecurityContext

README.md, charts/atlantis/Chart.yaml, charts/atlantis/ci/ci-init-config-values.yaml, charts/atlantis/templates/configmap-init-config.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Closes https://github.com/runatlantis/helm-charts/issues/227
- Add init container to install providers/plugins in a directory shared with atlantis, 
- The implementation is simple, enabling chart users to personalize/customize it, to prevent breaking changes I haven't reused the existing `initContainers` key
- Add new ci config file `ci-init-config-values.yaml` to ensure the feature works
<details>
<summary>Prepare environment (click to expand)</summary>
```sh
→ kind create cluster --name test-atlantis
Creating cluster "test-atlantis" ...
✓ Ensuring node image (kindest/node:v1.27.3) 🖼
✓ Preparing nodes 📦
✓ Writing configuration 📜
✓ Starting control-plane 🕹️
✓ Installing CNI 🔌
✓ Installing StorageClass 💾
Set kubectl context to "kind-test-atlantis"
You can now use your cluster with: …
```
=> feat(helm-chart): support adding providers/plugins

.github/workflows/stale.yml
As discussed on [slack](https://atlantis-community.slack.com/archives/C04ES70Q6E8/p1709114536848619).
Keep issues and PRs clean.
=> ci(stale): add action to cleanup stale issues

charts/atlantis/Chart.yaml, charts/atlantis/templates/configmap-repo-config.yaml
The last release v4.23.0 contains a typo / bug in the `configmap-repo-config.yaml` template where a `indent` is used instead of `nindent`, causing a templating error if the `repoConfig` value is set.
=> fix: fix indentation of repos.yaml in configmap-repo-config

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml
Fix nil pointer error with StatefulSet labels when set, introduced in #356.
```
[ERROR] templates/: template: atlantis/templates/statefulset.yaml:8:22: executing "atlantis/templates/statefulset.yaml" at <.Values.statefulSet.labels>: nil pointer evaluating interface {}.statefulSet
```
https://github.com/runatlantis/helm-charts/pull/356#discussion_r1516867355
=> fix: fix nil pointer error with StatefulSet labels when set

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json
Fixes #365. This changes the array item type back to string for extraArgs, which seems to have been erroneously changed in #356 
Even if this wasn't erroneously, it should've been a breaking change.
=> fix: fix values.schema.json for extraArgs

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Makes it an option to add a security context to the initConfig container
- I'm running atlantis in a very restricted cluster and it needs a specific security context
- I rendered the template and it looks good
=> Adds securityContext to initConfig

.github/linters/.jscpd.json, .github/workflows/lint-test.yaml, .github/workflows/linter.yaml, .github/workflows/release.yaml, .github/workflows/stale.yml
Fixes super-linter errors:
- sets stricter permissions to clear `checkov` errors
- excludes helm templates and tests from `jscpd` as it's expected to have duplicate content
After updating super-linter on https://github.com/runatlantis/helm-charts/pull/377, we starting getting error with `checkov` and `jscpd`. E.g. [helm-charts/actions/runs/8912806968](https://github.com/runatlantis/helm-charts/actions/runs/8912806968/job/24476999190?pr=381).
=> ci(atlantis): fix super-linter

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/statefulset_test.yaml
Fixes permissions for `/home/atlantis/.gitconfig` using `defaultMode` option
```yaml
→ kubectl explain statefulset.spec.template.spec.volumes.secret.defaultMode
GROUP:      apps
KIND:       StatefulSet
VERSION:    v1
FIELD: defaultMode <integer>
DESCRIPTION:
defaultMode is Optional: mode bits used to set permissions on created files
by default. Must be an octal value between 0000 and 0777 or a decimal value
between 0 and 511. YAML accepts both octal and decimal values, JSON requires
decimal values for mode bits. Defaults to 0644. Directories within the path
are not affected by this setting. This might be in conflict with other
options that affect the file mode, like fsGroup, and the result can be other
mode bits set.
```
Reported on https://github.com/runatlantis/helm-charts/issues/222 …
=> fix(atlantis): permissions for .gitconfig file

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/README.md.gotmpl, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
By default `init-shared-path` is read-only mounted without the possibility to mount it read-write. This PR expose the `readOnly` setting of the `volumeMount` to be able to manage it through values file.
We used to build a custom `atlantis` image to be able to embed additional tools required by custom workflows defined server-side (like `aws-cli` or `asdf` to handle `terraform`, `terragrunt`, `opentofu`, `kubectl` and others). Although it works just fine, we had to maintain our custom image.
Since `initConfig` object, we have been able to move the instruction from our custom `Dockerfile` to the `initConfig.script` value.
The main issue is that the `initConfig.sharedDir` is mounted read-write on the init container, but is mounted read-only on the main container.
As we're using `asdf` is all …
=> ✨ expose init-shared-path readOnly var

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/values.yaml
For security context on init container, you're using `.Values.initConfig.containerSecurityContext` (as seen in [here](https://github.com/runatlantis/helm-charts/blob/7693bfd4a0f8505d5ea74cfcc27f4e02064074df/charts/atlantis/templates/statefulset.yaml#L187C58-L187C82)), but you're referencing `securityContext` (as seen in [here](https://github.com/runatlantis/helm-charts/blob/7693bfd4a0f8505d5ea74cfcc27f4e02064074df/charts/atlantis/values.yaml#L571C1-L571C22))
I'm not sure it require a minor version bump as this is just a typo fix, schema was already correct.
closes #392
=> ✏️ fix typo on var name

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
Adds dnsConfig property on Atlantis.
Allows dns resolution for specific domains.
unit tests made successfully.
```
Installed plugin: unittest
PASS  test pvc charts/atlantis/tests/pvc_test.yaml
PASS  test secret-api for api secret   charts/atlantis/tests/secret-api_test.yaml
PASS  test secret-aws for aws  charts/atlantis/tests/secret-aws_test.yaml
PASS  test secret-basic-auth for git basic-auth secret charts/atlantis/tests/secret-basic-auth_test.yaml
PASS  test secret-gitconfig for gitconfig      charts/atlantis/tests/secret-gitconfig_test.yaml
PASS  test secret-netrc for netrc      charts/atlantis/tests/secret-netrc_test.yaml
PASS  test secret-service-account for serviceAccountSecrets    charts/atlantis/tests/secret-service-account_test.yaml
PASS  test secret-webhook for git webhook …
```
=> feat: add dnsConfig to Atlantis

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/_helpers.tpl, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/statefulset_test.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
We got a use-case where we need to defined the `PATH` environment variable through the `.Values.environment` [node](https://github.com/runatlantis/helm-charts/blob/e984db5a37cee1b1eecff8bb43702105fb8227a5/charts/atlantis/values.yaml#L475) for the statefulset, and we had some issues due to duplicate entries.
When `.Values.initConfig` is enabled, the chart actually add a [`PATH` environment variable](https://github.com/runatlantis/helm-charts/blob/e984db5a37cee1b1eecff8bb43702105fb8227a5/charts/atlantis/templates/statefulset.yaml#L488).
The issue is due to how Kubernetes handle duplicate envvars definition, when a referenced key is present in multiple resources, the value associated with the last source will override all previous values.
As `.Values.initConfig` variable is defined later in …
=> Better handling of PATH env var with initConfig

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
- fixed file name typo in init config script for TAC file
- it gives some errors while trying to update the version of those deps
- [ x ] I have tested my changes by ...
=> fix(helm-chart): script file name typo in init config

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/service.yaml, charts/atlantis/tests/service_test.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
Allow setting portName field on service
When using istio. there is a rule that sets the name of the service port. For this reason, we enable the portname setting.
local test
https://github.com/istio/istio/issues/11509
=> fix(chart): Allow setting portName on service

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
- Updated the versions in the `initConfig` script for the examples of `terragrunt` and `terragrunt-atlantis-config`.
- Bumped the `terragrunt` version from `v0.47.0` to `v0.67.5` and the `terragrunt-atlantis-config` version from `1.16.0` to `1.18.0`.
- Adjusted the download commands and SHA256 checks for the new versions of the tools.
- Keeping the versions of `terragrunt` and `terragrunt-atlantis-config` up to date ensures better security, performance, and compatibility.
- The new versions include bug fixes and improvements, which enhance the functionality of the `initConfig` example.
- It provides up-to-date examples for users who want to configure their Atlantis pods with these tools.
- N/A
=> chore(chart): bump initConfig script example versions

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
Helm templating syntax requires that the boolean keyword goes before the two values that are being compared.
Example:
```
{{if and value1 value2}}
```
instead of
```
{{if value1 and value2}}
```
This fixes the issue with respect to the following error when upgrading the helm chart:
```
Error: UPGRADE FAILED: template: atlantis/templates/statefulset.yaml:44:47: executing "atlantis/templates/statefulset.yaml" at <.Values.dnsPolicy>: dnsPolicy is not a method but has arguments
```
This fix has been tested locally and the manifests render out properly.
closes #405
=> fix(templates): Fix and boolean on line 44 of statefulset.yaml

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/statefulset_test.yaml, charts/atlantis/values.yaml
- Provide ability to use the `service.TargetPort` key to define alternative ports for running atlantis.
- Extended documentation for the `targetPort` key to include implications.
- There is partial support for custom ports, but it is not extended to include all port related configurations. This allows for a hollistic approach to custom ports.
Ive extended the helm tests to cover this use-case.
`closes #420 `
=> Fix(atlantis) Unable to use custom port #420

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/servicemonitor.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Adds metricRelabelings value under ServiceMonitor to allow customization of the ingested metrics/labels. See Prometheus Operator for more info - https://github.com/prometheus-operator/prometheus-operator/blob/d2599cfe67beb97b9208e79422457b0f7cde3c4a/Documentation/api.md#endpoint
- Prevents potential cardinality issues, allows user control over metric ingestion spend
- diff output of enabled ServiceMonitor with/without new value
```
--- 219,229 ----
- port: atlantis
interval: 30s
path: /metrics
+     metricRelabelings:
+       - action: drop
+         regex: atlantis_project_apply_execution_.*
+         sourceLabels:
+         - __name__
```
- ran `make unit-test-run-atlantis`
```
PASS  test configmap-gitconfig-init for gitconfig	charts/atlantis/tests/configmap-gitconfig-init_test.yaml …
```
=> feat: add metricRelabelings support to ServiceMonitor

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/statefulset_test.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
- Added `redisSecretPasswordKey` value
- Kept previous `password` value as default for backward-compatibility
This allows users to override the default `password` key used when specifying an existing `Secret` for Redis. This makes for a more seamless integration with popular third-party Redis Helm charts.
For example, the Bitnami Redis chart creates a secret called `<release>-redis` with a key called `redis-password` whose value is the password generated for that Redis distribution. Allowing users to specify an arbitrary key name means they can seamlessly integrate that Redis chart with this Atlantis chart and use the same secret.
I have tested this successfully in an Amazon EKS cluster.
N/A
=> Redis Secret Password Key

charts/atlantis/Chart.yaml, charts/atlantis/templates/configmap-config.yaml, charts/atlantis/templates/configmap-gitconfig-init.yaml, charts/atlantis/templates/configmap-init-config.yaml, charts/atlantis/templates/configmap-repo-config.yaml, charts/atlantis/templates/ingress.yaml, charts/atlantis/templates/podmonitor.yaml, charts/atlantis/templates/pvc.yaml, charts/atlantis/templates/role.yaml, charts/atlantis/templates/rolebinding.yaml, charts/atlantis/templates/secret-api.yaml, charts/atlantis/templates/secret-aws.yaml, charts/atlantis/templates/secret-basic-auth.yaml, charts/atlantis/templates/secret-gitconfig.yaml, charts/atlantis/templates/secret-netrc.yaml, charts/atlantis/templates/secret-redis.yaml, charts/atlantis/templates/secret-service-account.yaml, charts/atlantis/templates/secret-webhook.yaml, charts/atlantis/templates/service.yaml, charts/atlantis/templates/serviceaccount.yaml, charts/atlantis/templates/servicemonitor.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/templates/tests/test-atlantis-configmap.yaml, charts/atlantis/templates/tests/test-atlantis-pod.yaml, charts/atlantis/templates/webhook-ingress.yaml, charts/atlantis/tests/misc_test.yaml
On `helm install` or `upgrade`, the `--namespace` flag is respected regardless. 
However, when using this chart for static templating, the`--namespace` flag is ignored because the templates do not explicitly set `.metadata.namespace` to `.Release.Namespace`, making it cumbersome to customize the namespace.
=> fix(chart): explicitly set namespace based on release

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/README.md.gotmpl, charts/atlantis/templates/NOTES.txt, charts/atlantis/templates/secret-webhook.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/secret-webhook_test.yaml, charts/atlantis/tests/statefulset_test.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
Add support for Gitea.
It's clearly in the scope of this project.
I have successfully deployed an Atlantis instance using this feature.
Replaces https://github.com/runatlantis/helm-charts/pull/416
Closes https://github.com/runatlantis/helm-charts/issues/403
=> Add support for Gitea

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/secret-api.yaml, charts/atlantis/templates/secret-aws.yaml, charts/atlantis/templates/secret-basic-auth.yaml, charts/atlantis/templates/secret-gitconfig.yaml, charts/atlantis/templates/secret-netrc.yaml, charts/atlantis/templates/secret-redis.yaml, charts/atlantis/templates/secret-service-account.yaml, charts/atlantis/templates/secret-webhook.yaml, charts/atlantis/values.schema.json, charts/atlantis/values.yaml
Allow adding annotations to secret resources.
My use case is that I want to use vault-webhool to reflect secrets without define annotations for all resources when we use the extraAnnotations param.
=> feat(annotations): add secret annotations

charts/atlantis/Chart.yaml, charts/atlantis/templates/statefulset.yaml, charts/atlantis/tests/statefulset_test.yaml
Use ATLANTIS_DEFAULT_TF_DISTRIBUTION instead of deprecated ATLANTIS_TF_DISTRIBUTION
Fixes #453
=> Use ATLANTIS_DEFAULT_TF_DISTRIBUTION instead of deprecated ATLANTIS_TF_DISTRIBUTION

README.md
replace relative ref to values.yaml with full external link because this branch doesn't have any of the other files, including the referenced `charts/atlantis/values.yaml` file
Currently, the values.yaml as interpreted on the docs visible here:https://runatlantis.github.io/helm-charts/ are pointing to https://runatlantis.github.io/charts/atlantis/values.yaml & returning a 404
closes issue opened in runatlantis/atlantis project: https://github.com/runatlantis/atlantis/issues/5675
I also noticed these docs are pretty out of date compared to the `README.md` on the main branch, however as this is my first contribution to this repo, I figured it's best to start small. On maintainers desire, I can do a fuller copy to this `gh-pages` branch
=> the referenced file DNE on the gh-pages branch, use hard link
