runatlantis/helm-charts

charts/atlantis/Chart.yaml, charts/atlantis/README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
#6 
upd. seems like `Lint Code Base / Lint Code Base (pull_request)` shows issues what exist before my PR, please check
=> Add init containers support

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to runatlantis/atlantis#1874
closes #71
=> update default atlantis to 0.17.5

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to runatlantis/atlantis#1965
=> update default atlantis to 0.18.0

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to runatlantis/atlantis#1976
cc @lkysow
=> update default atlantis to 0.18.1

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to https://github.com/runatlantis/atlantis/pull/2018
=> update default atlantis to 0.18.2

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to runatlantis/atlantis#2078
=> update default atlantis to 0.18.3

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to runatlantis/atlantis#2122
=> update default atlantis to 0.19.1

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to https://github.com/runatlantis/atlantis/pull/2133
=> update default atlantis to 0.19.2

README.md
=> chore: Helm3 does not use --name option

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
=> Release v1.9.4

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
relates to https://github.com/runatlantis/atlantis/pull/2373
=> update default atlantis to 0.19.6

charts/atlantis/templates/ingress.yaml, charts/atlantis/values.yaml
This allows protecting the web ui behind auth while still exposing the webhook.
=> Make it possible to create several service backends

charts/atlantis/Chart.yaml
=> release v0.19.7

README.md, charts/atlantis/templates/statefulset.yaml, charts/atlantis/values.yaml
Relates to #93, Implements #82
=> feat: allow override of ca-certificates.crt

charts/atlantis/templates/servicemonitor.yaml, charts/atlantis/values.yaml
Add SVC monitor to scrape prom metrics
Closes https://github.com/runatlantis/helm-charts/issues/170
=> Add svc monitor

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
=> Release v0.19.8

charts/atlantis/Chart.yaml
bumping release for api support
=> Release 4.0.9

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Update chart for Atlantis v1.9.9
=> Atlantis release 1.9.9

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Updating to new base image due to Security Updates
=> Updating to new base image

charts/atlantis/Chart.yaml
=> release: bump version

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
=> Release 0.21.0

charts/atlantis/values.yaml
- add environment values example
- better documentation. This is commonly asked about.
- https://github.com/runatlantis/helm-charts/issues/111#issuecomment-1014769945
=> docs: add environment values example

charts/atlantis/Chart.yaml, charts/atlantis/values.yaml
Sync for Atlantis 0.23.0 release
new release
=> Updating for release 0.23.0

.github/renovate.json5, charts/atlantis/Chart.yaml
- Add renovate to bump appVersion
- users use the appVersion to keep track of atlantis version so its important to keep it up to date
- https://docs.renovatebot.com/modules/datasource/
- https://docs.renovatebot.com/presets-schedule/
- https://github.com/gabe565/charts/blob/d15d62008e74e0ffaf95862696711427601bafa8/.github/renovate.json
- https://github.com/gabe565/charts/blob/d15d62008e74e0ffaf95862696711427601bafa8/charts/borgmatic/Chart.yaml#L8
- https://github.com/runatlantis/atlantis/blob/main/.github/renovate.json5
=> chore: add renovate to bump appVersion

charts/atlantis/Chart.yaml
Bump app version to latest stable release: https://github.com/runatlantis/atlantis/releases/tag/v0.23.5
* https://github.com/runatlantis/atlantis/releases/tag/v0.23.5
Deployed Locally
=> fix(app_version): Bump App Version

charts/atlantis/Chart.yaml
Bump App Version
Default install should be latest stable release.
=> Bump default app version to 0.24.2

charts/atlantis/Chart.yaml, charts/atlantis/values.schema.json
- Add boolean and integer type to environment values 
- made problems to certain users
- templating the chart
=> Fix values.schema.json for environment types

charts/atlantis/Chart.yaml
Update Atlantis to the [recently released v0.27.0](https://github.com/runatlantis/atlantis/releases/tag/v0.27.0)
=> release: update atlantis to v0.27.0

CODEOWNERS, charts/atlantis/Chart.yaml
- Add GMartinez-Sisti as chart maintainer
=> chore(maintainers): add GMartinez-Sisti

.github/renovate.json5, .github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/atlantis/Chart.yaml, renovate.json
Fixes the Renovate config (by removing the duplicate config file) and did some necessary config migrations
Renovate was not configured properly because of the duplicate file. I also saw some (IMO) possibilities for improvements. Also, with the current configuration Renovate wouldn't have recognized all the dependencies.
- Closes #295 (this time for real!)
=> chore: fixed renovate config
